env: local
storage:
  type: "sqlite"
  config:
    sqlite_path: "./storage/url.db"
    mongo_url: "mongodb://localhost:27017"
http_server:
  address: "http://localhost:8082"
  timeout: 4s
  idle_timeout: 60s
github:
  client_id: "CLIENT_ID"
  client_secret: "SECRET"
auth:
  jwt_secret_key: "secret"
  git_hub_org: "ORG"